StudX/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.shortcuts import redirect
from django.views.generic import TemplateView

import dashboard.urls, student.urls, user.urls, communication.urls, configuration.urls, schedule.urls

# Simple views for new pages
def teachers_view(request):
    from django.shortcuts import render
    return render(request, 'teachers_list.html')

def formations_view(request):
    from django.shortcuts import render
    return render(request, 'formations_list.html')

def payments_view(request):
    from django.shortcuts import render
    return render(request, 'payments_list.html')

urlpatterns = [
    url(r'^tinymce/', include('tinymce.urls')),
    path('', lambda request: redirect('dashboard:dashboard'), name='root'),
    path('schedule/', include(schedule.urls, namespace='schedule')),
    path('configuration/', include(configuration.urls, namespace='configuration')),
    path('communication/', include(communication.urls, namespace='communication')),
    path('user/', include(user.urls, namespace='user')),
    path('dashboard/', include(dashboard.urls, namespace='dashboard')),
    path('student/', include(student.urls, namespace='student')),
    # New pages
    path('teachers/', teachers_view, name='teachers'),
    path('formations/', formations_view, name='formations'),
    path('payments/', payments_view, name='payments'),
]

student/urls.py
# /StudX_dir/StudX/student/urls.py

from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from student import views

app_name = 'student'

urlpatterns = [
	path('student_list', views.student_list, name='student_list'),
	path('list', views.student_list, name='list'),  # Alternative URL
	path('add/', views.add_student, name='add_student'),
	path('<uuid:student_id>/toggle-payment/', views.toggle_payment, name='toggle_payment'),
	path('<uuid:student_id>/delete/', views.delete_student, name='delete_student'),
	path('<uuid:uuid>/details/', views.student_detail, name='student_detail'),
	path('<uuid:uuid>/details/', views.view_student, name='view_student'),
	path('<uuid:student_uuid>/note/create', views.create_edit_student_note, name='create_student_note'),
	path('<uuid:student_uuid>/note/<uuid:note_uuid>/edit', views.create_edit_student_note, name='edit_student_note'),
	path('<uuid:student_uuid>/note/<uuid:note_uuid>/delete', views.delete_student_note, name='delete_student_note'),
	path('disciplines/', views.disciplines_list, name='disciplines_list'),
	path('<int:id>/details/', views.discipline_details, name='discipline_details'),
	path('discipline/create/', views.create_edit_discipline, name='create_discipline'), 
	path('discipline/<int:id>/edit/', views.create_edit_discipline, name='edit_discipline'), 
	path('discipline/<int:id>/delete/', views.delete_discipline, name='delete_discipline'),
	path('attendances/', views.attendance_list, name='attendance_list'),
	path('<slug:inout_str>/', views.in_out_list, name='in_out_list'),
	path('<slug:inout_str>/<int:id>/details/', views.in_out_details, name='in_out_details'),
	path('<slug:inout_str>/<int:id>/delete/', views.delete_inout, name='delete_inout'),
	path('<slug:inout_str>/create/', views.create_edit_inout, name='create_inout'),
	path('<slug:inout_str>/<int:id>/edit/', views.create_edit_inout, name='edit_inout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
# /StudX_dir/StudX/user/urls.py

from django.urls import path
from django.conf.urls.static import static
from django.conf.urls import url
from user.forms import CustomAuthForm
from django.contrib.auth import views as auth_views

from user import views

app_name = 'user'

urlpatterns = [
	url(r'^logout/$', views.logout_studx, name='logout'),
	path('login/', auth_views.LoginView.as_view(), name='login'),
	path('logout/', auth_views.LogoutView.as_view(), name='Logout'),
	path('list/', views.user_list, name='user_list'),
	path('new/', views.create_edit_user, name='create_user'),
	path('<int:user_id>/edit/', views.create_edit_user, name='edit_user'),
	path('<int:user_id>/delete/', views.delete_user, name='delete_user'),
]

student/models.py
# /StudX_dir/StudX/student/models.py

# System imports
from django.db import models
from django.conf import settings
from datetime import datetime, date, time, timedelta
from django.utils.translation import gettext as _ # for internationalization
from django.utils import timezone
from django.contrib.auth.models import User
from tinymce.models import HTMLField
import uuid

# Apps imports
from common.utils import *

# Models imports
from user.models import User
from configuration.models import Classes

class StudentManager(models.Manager):
    def get_queryset(self):
        return super(StudentManager, self).get_queryset().filter(status=1)

class Student(models.Model):
	__tablename__ = 'Student'

	uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
	matricule = models.CharField(max_length=10, unique=True) # Personal number
	fname = models.CharField(_('First name'),max_length=45, null=False) # First name
	lname = models.CharField(_('Last name'),max_length=45, null=False) # Last name
	status = models.IntegerField(choices=STUDENT_STATUS, default=ACTIVE)
	bday = models.DateField(_('Birthday'), null=False) # Birthday
	country_of_birth = models.CharField(max_length=3, choices=COUNTRIES, blank=True, null=True)
	gender = models.IntegerField(choices=GENDER, default=EMPTY, null=True) # Gender 'M' for male or 'F' for female
	picture = models.ImageField(upload_to='%Y/Profile/', verbose_name=_('Picture'), 
		null=True, 
		blank=True, 
		width_field = 'width_field', 
		height_field = 'height_field') # Location of the student's picture
	height_field = models.IntegerField(default=0)
	width_field = models.IntegerField(default=0)
	start_date = models.DateField(auto_now=True, null=True)
	end_date = models.DateField(default='1000-01-01', null=True)
	ICE_details = HTMLField('Emergency infos', null=True, blank=True) # "in case of ermegency" information
	classe = models.ForeignKey(to='configuration.Classes', related_name='student_classe', on_delete=models.SET_NULL, null=True, blank=True)
	address = models.ForeignKey(to='Address', related_name='student_address', on_delete=models.SET_NULL, null=True, blank=True)
	parent= models.ManyToManyField(to='Parents', through='Relationship' , related_name='student_parent', blank=True)
	comment = models.TextField(max_length=255, null=True, blank=True) # Free text
	created_at = models.DateTimeField(editable=False, auto_now_add=True, auto_now=False, null=True, blank=True) # Creation TIMESTAMP
	updated_at = models.DateTimeField(editable=False, auto_now_add=False, auto_now=True, null=True, blank=True) # Last update TIMESTAMP
	creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, related_name='student_created_by', null=True) # Creator username
	last_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, related_name='student_updated_by', null=True, blank=True) # Last user username
	

	# get all student having an active status
	objects = StudentManager()
	
	def __str__(self):
		return '{}, {} ({})'.format(self.fname, self.lname, self.matricule)
		
	def get_age(self):
		age = date.today() - self.bday
		age = age.days / 365.2425
		return int(age)
	
	class Meta:
		verbose_name = _('Student')
		verbose_name_plural = _('Students')
		
		
# Define Child - Guardian relationship
# Can be Mother, Father, etc.		
class Relationship(models.Model):
	__tablename__ = 'Relationship'
	
	student = models.ForeignKey(to='Student', on_delete=models.CASCADE, related_name='student_membership', null=True, blank=True)
	parent = models.ForeignKey(to='Parents', on_delete=models.CASCADE, related_name='parent_membership', null=True, blank=True)
	relation = models.IntegerField(choices=RELATIONSHIP, default=EMPTY, null=True, blank=True)
	is_ICE = models.BooleanField(default=True)
	is_InCharge = models.BooleanField(default=False)
	
	def __str__(self):
		return '{0} {1} - {2} {3}'.format(self.student.fname, self.student.lname, self.parent.fname, self.parent.lname)
	
	class Meta:
				ordering = ('is_ICE','is_InCharge')
		
class Parents(models.Model):
	__tablename__ = 'Parents'

	uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
	fname = models.CharField(_('First name'),max_length=45, null=False) # First name
	lname = models.CharField(_('Last name'),max_length=45, null=False) # Last name
	status = models.IntegerField(choices=STATUS, default=ACTIVE)
	bday = models.DateField(_('Birthday'), null=True) # Birthday
	gender = models.IntegerField(choices=GENDER, default=EMPTY, null=True) # Gender 'M' for male or 'F' for female
	address = models.ForeignKey(to='Address', related_name='parent_address', on_delete=models.SET_NULL, null=True, blank=True)
	
	comment = models.CharField(max_length=255, null=True, blank=True) # Free text
	created_at = models.DateTimeField(editable=False, auto_now_add=True, auto_now=False, null=True, blank=True) # Creation TIMESTAMP
	updated_at = models.DateTimeField(editable=False, auto_now_add=False, auto_now=True, null=True, blank=True) # Last update TIMESTAMP
	creator = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='parent_created_by', on_delete=models.SET_NULL, null=True) # Creator username
	last_user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='parent_updated_by', on_delete=models.SET_NULL, null=True, blank=True) # Last user username
	
	def __str__(self):
		return '{}, {}'.format(self.fname, self.lname)
		
	class Meta:
		verbose_name = _('Parent')
		verbose_name_plural = _('Parents')	

class Parent_hasContacts(models.Model):
	__tablename__ = 'Parent_hasContacts'
	
	parent = models.ForeignKey(to='Parents', related_name='parent_hascontact', on_delete=models.CASCADE)
	contact = models.CharField(_('contact'), max_length=255, null=True)
	type = models.IntegerField(choices=CONTACT_TYPE, null=True)
	comment = models.CharField(max_length=255, null=True, blank=True) # Free text
	created_at = models.DateTimeField(editable=False, auto_now_add=True, auto_now=False, null=True, blank=True) # Creation TIMESTAMP
	updated_at = models.DateTimeField(editable=False, auto_now_add=False, auto_now=True, null=True, blank=True) # Last update TIMESTAMP
	creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, related_name='parentcontact_created_by', null=True) # Creator username
	last_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, related_name='parentcontact_updated_by', null=True, blank=True) # Last user username
	
	def __str__(self):
		return '{0}-{1}'.format(self.type, self.contact)
	
	class Meta:
		ordering = ('type',)
		verbose_name = _("Parent's contact")
		verbose_name_plural = _("Parent's contacts")
		
class Student_hasContacts(models.Model):
	__tablename__ = 'Student_hasContacts'
	
	student = models.ForeignKey(Student, related_name='student_hascontact' ,on_delete=models.CASCADE)
	contact = models.CharField(_('contact'), max_length=255, null=True)
	type = models.IntegerField(choices=CONTACT_TYPE, null=True)
	
	comment = models.CharField(max_length=255, null=True, blank=True) # Free text
	created_at = models.DateTimeField(editable=False, auto_now_add=True, auto_now=False, null=True, blank=True) # Creation TIMESTAMP
	updated_at = models.DateTimeField(editable=False, auto_now_add=False, auto_now=True, null=True, blank=True) # Last update TIMESTAMP
	creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, related_name='studentcontact_created_by', null=True) # Creator username
	last_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, related_name='studentcontact_updated_by', null=True, blank=True) # Last user username
	
	def __str__(self):
		return '{0}-{1}'.format(self.type, self.contact)
	
	class Meta:
		verbose_name = _("Student's contact")
		verbose_name_plural = _("Student's contacts")	

def user_directory_path(instance, filename):
    # files are uploaded to MEDIA_ROOT/user_<id>/<filename>
    return '%Y/user_{0}/{1}'.format(instance.student.matricule, filename)
	
class Student_hasDocs(models.Model):
	__tablename__ = 'Student_hasdocs'

	title = models.CharField(_('Title'),max_length=100, null=True, blank=True)
	location = models.FileField(_('Location'),upload_to=user_directory_path, null=True, blank=True)
	description = models.CharField(_('Description'),max_length=255, null=True, blank=True)
	student = models.ForeignKey(Student, on_delete=models.CASCADE)
	
	created_at = models.DateTimeField(editable=False, auto_now_add=True, auto_now=False, null=True, blank=True) # Creation TIMESTAMP
	updated_at = models.DateTimeField(editable=False, auto_now_add=False, auto_now=True, null=True, blank=True) # Last update TIMESTAMP
	creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, related_name='studentdoc_created_by', null=True) # Creator username
	last_user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, related_name='studentdoc_updated_by', null=True, blank=True) # Last user username

	def __str__(self):
		return '{}'.format(self.title)
	
	class Meta:
		verbose_name = _("Student's document")
		verbose_name_plural = _("Student's documents")		

class Address(models.Model):
	__tablename__ = 'Address'
	
	street = models.CharField(_('street'), max_length=255, null=True, blank=True)
	city = models.CharField(_('city'), max_length=255, null=True, blank=True)
	zip = models.IntegerField(_('postal code'), null=True, blank=True)

	class Meta:
		unique_together = ('street', 'city',)
		verbose_name = _("Address")
		verbose_name_plural = _("Addresses")

	def __str__(self):
		return self.street		


		
class Disciplines(models.Model):
	"""
		Misbehaviours are recorded in this table.
		If one or several sanction(s) is/are associated to a misbehaviour the description is in the 'Disciplines_Details' class to handle occurence.
		E.g. a student talked during a lesson. The sanction is to stay after class on Wednesday 18 and Wesneday 28. 

student/forms.py
# /StudX_dir/StudX/student/forms.py #

from django import forms
from django.forms.formsets import formset_factory
from tinymce.widgets import TinyMCE

# import core.models
from django.contrib.auth.models import User
from student.models import Disciplines, Discipline_type, Disciplines_Details, Arrivals_Departures, Attendances, Student_Notes


# *** Code start here ***
		
class DisciplineForm(forms.ModelForm):
	class Meta:
		model = Disciplines
		# template_name = "core/discipline_form.html"
		fields = ['type','fact_date' , 'student', 'status', 'issuer', 'location', 'motif', 'comment']
		

		
class DisciplineDetailsForm(forms.ModelForm):
	class Meta:
		model = Disciplines_Details
		fields = [
			'start_date',
			'start_time',
			'finish_date',
			'finish_time',
			'description'
		]
		
		widgets = {
			'description': forms.Textarea(attrs={'rows': 1}),
		}
		
DisciplineDetailsFormSet = formset_factory(DisciplineDetailsForm, extra=0)

DisciplineDetailsInlineFormSet = forms.inlineformset_factory(Disciplines, Disciplines_Details, fields = ('id','start_date','start_time','finish_date','finish_time','description'), extra=1)

class inoutForm(forms.ModelForm):
	class Meta:
		model = Arrivals_Departures
		fields = (
			'student',
			'justification',
			'document',
			'apply_on_date',
			'apply_on_time',
			'scheduled_time',
			'time_delta',
			'is_excused',
			'comment'
			)

class StudentNoteForm(forms.ModelForm):
	class Meta:
		model = Student_Notes
		fields = (
			'title',
			'content',
			'note_category',
			)

student/templates/student/student_details/student_details_discipline.html
{# /StudX_dir/StudX/student/templates/student/student_details_discipline.html #}

{% load i18n student_tags %}

<!-- Statistiques list group -->
<div class="row justify-content-md-center">
	<div class="col">
		<ul class="list-group">
			<!-- header -->
			<li class="list-group-item active d-flex list-group-item-action justify-content-between align-items-center"><i class="fas fa-user-times"></i> {% trans "Disciplinary Infractions" %}<span class="badge badge-danger badge-pill">{{ student_disciplines_count }}</span></li>
			
			{% for item in student_discipline_stats %}
				<li class="list-group-item d-flex list-group-item-action justify-content-between align-items-center">
					{{item.type__sanction}}
					<span class="badge badge-primary badge-pill">{{ item.num_sanction }}</span>
				</li>
			{% endfor %}
		</ul>
	</div>
	
	<div class="col">
		<ul class="list-group">
			<!-- header -->
			<li class="list-group-item active d-flex list-group-item-action justify-content-between align-items-center"><i class="fas fa-calendar-times"></i> {% trans "Absences"%}<span class="badge badge-danger badge-pill">{{ student_absences_count }}</span></li>
			
			{% for item in student_absences_stats %}
				{% if item.is_excused  %}
					<li class="list-group-item d-flex list-group-item-action justify-content-between align-items-center">
						{% trans "Justified" %}
						<span class="badge badge-primary badge-pill">{{ item.num_abscences }}</span>
					</li>
				{% else %}
					<li class="list-group-item d-flex list-group-item-action justify-content-between align-items-center">
						{% trans "Non justified" %}
						<span class="badge badge-primary badge-pill">{{ item.num_abscences }}</span>
					</li>
				{% endif %}
			{% endfor %}
		</ul>
	</div>
	
	<div class="col">
		<ul class="list-group">
			<!-- header -->
			<li class="list-group-item active d-flex list-group-item-action justify-content-between align-items-center"><i class="fas fa-clock"></i> {% trans "Tardiness"%}<span class="badge badge-danger badge-pill">{{ student_tardiness_count }}</span></li>
			
			{% for item in student_tardiness_stats %}
				{% if item.is_excused  %}
					<li class="list-group-item d-flex list-group-item-action justify-content-between align-items-center">
						{% trans "Justified" %}
						<span class="badge badge-primary badge-pill">{{ item.num_tardiness }}</span>
					</li>
				{% else %}
					<li class="list-group-item d-flex list-group-item-action justify-content-between align-items-center">
						{% trans "Non justified" %}
						<span class="badge badge-primary badge-pill">{{ item.num_tardiness }}</span>
					</li>
				{% endif %}
			{% endfor %}
		</ul>
	</div>
</div>
<!-- Statistiques list group END -->

<!-- Disciplines table -->
{% if student_disciplines %}
<div class="row mt-3">
	<div class="col"> 
		<div class="card">
			<div class="card-header p-3 mb-2 bg-primary text-white"><i class="fas fa-user-times"></i> {% trans "Disciplinary Infractions" %}</div>
			<div class="card-body">
				<div class="table-responsive">
					<table class="table table-bordered" id="disciplinesTable" width="100%" cellspacing="0">
					   <thead>
						  <tr>
							<th>{% trans "Date" %}</th>
							<th>Sanctions</th>
							<th>{% trans "Creator" %}</th>
							<th>{% trans "Motif" %}</th>
							<th style="width: 20px;">Status</th>
							<th style="width: 20px;">Action</th>
						  </tr>
					   </thead>
					   <tbody>
						  {% for discipline in student_disciplines %}
							  <tr>
								<td>{{ discipline.fact_date }}</td>
								<td><a href="{% url 'student:discipline_details' discipline.id %}">{% if discipline.type.sanction %}{{ discipline.type.sanction }}{% else %}{% trans "No sanction" %}{% endif %}</a></td>
								<td>{{ discipline.creator.get_full_name }}</td>
								<td>{{ discipline.motif|truncatechars_html:50|safe }}</td>
								<td><span class="badge badge-{{ discipline.status|get_status_color }} badge-pill">{{ discipline.get_status_display }}</span></td>
								<td class="actions">
								<div class="btn-group btn-group-sm" role="group">
								   <a class="btn btn-outline-info btn-sm" href="{% url 'student:discipline_details' discipline.id %}"><i class="fas fa-eye"></i> </a>
								   {% if discipline.creator == user %}
										<a class="btn btn-outline-info btn-sm" href="{% url 'student:edit_discipline' discipline.id %}"><i class="fas fa-pencil-alt"></i> </a>
										<a class="btn btn-outline-info btn-sm" data-toggle="modal" data-target="#DisciplineDeleteModal" href="#""><i class="fas fa-trash-alt"></i> </a>   
								</div>
										{% include 'student/disciplines/discipline_delete_modal.html' %}
									{% endif %}
								 </td>
							  </tr>
						  {% endfor %}
					   </tbody>
					</table>
				</div> <!-- table-responsive - END -->
			</div> <!-- card-body - END -->
		</div> <!-- card - END -->
	</div> <!-- col - END -->
</div> <!-- row mt-3 - END -->
{% endif %}
<!-- Disciplines table END -->

<!-- Tardiness table -->
{% if student_tardiness %}
<div class="row mt-3">
	<div class="col">
		<div class="card">
			<div class="card-header p-3 mb-2 bg-primary text-white"><i class="fas fa-clock"></i> {% trans "Tardiness" %}</div>
			<div class="card-body">
				<div class="table-responsive">
					<table class="table table-bordered" id="tardinessTable" width="100%" cellspacing="0">
					   <thead>
						  <tr>
							<th style="width: 10px;"></th>
							<th>Date</th>
							<th>{% trans "Time" %}</th>
							<th>{% trans "Difference" %}</th>
							<th>{% trans "Justification" %}</th>
							<th style="width: 20px;">Action</th>
						  </tr>
					   </thead>
					   <tbody>
						  {% for element in student_tardiness %}
							  <tr>
								<td>
									{% if element.is_excused  %}
										<i class="fas fa-clock text-success" data-toggle="tooltip" title='{% trans "Justified" %}'></i>
									{% else %}
										<i class="fas fa-clock text-danger" data-toggle="tooltip" title='{% trans "Non justified" %}'></i>
									{% endif%}
								</td>
								<td>{{ element.apply_on_date }}</td>
								<td>{{ element.apply_on_time }}</td>
								<td>{{ element.time_delta|time:"H:i" }}</td>
								<td>{{ element.justification }}</td>
								<td>
									<div class="btn-group btn-group-sm" role="group">
										<a class="btn btn-outline-info btn-sm" href="{% url 'student:in_out_details' 'Arrival' element.id %}"><i class="fas fa-eye"></i> </a>
										{% if element.creator == user %}
										<a class="btn btn-outline-info btn-sm" href=""><i class="fas fa-pencil-alt"></i> </a>
										<a class="btn btn-outline-info btn-sm" href="#"><i class="fas fa-trash-alt"></i> </a>
										{% endif %}
									</div>
								</td>
							  </tr>
						  {% endfor %}
					   </tbody>
					</table>
				</div><!-- table-responsive - END -->
			</div> <!-- card-body - END -->
		</div> <!-- card - END -->
	</div><!-- col - END -->
</div><!-- row mt-3 - END -->
{% endif %}
<!-- Tardiness table END-->


<!-- Attendances table -->
{% if student_attendances %}
<div class="row mt-3">
	<div class="col">
		<div class="card">
			<div class="card-header p-3 mb-2 bg-primary text-white">
			<i class="fas fa-calendar-times"></i> {% trans "Absences" %}</div>
			<div class="card-body">
				<div class="table-responsive">
					<table class="table table-bordered" id="attendanceTable" width="100%" cellspacing="0">
					   <thead>
						  <tr>
							<th style="width: 10px;"></th>
							<th>Date</th>
							<th>{% trans "Motif" %}</th>
							<th style="width: 20px;">Action</th>
						  </tr>
					   </thead>
					   <tbody>
						  {% for element in student_attendances %}
							  <tr>
								<td>
									{% if element.is_excused  %}
										<i class="fas fa-circle text-success" data-toggle="tooltip" title='{% trans "Justified" %}'></i>
									{% else %}
										<i class="fas fa-circle text-danger" data-toggle="tooltip" title='{% trans "non justified" %}'></i>
									{% endif%}
								</td>
								<td>{{ element.start_date }}</td>
								<td>{{ element.motif }}</td>
								<td>
									<div class="btn-group btn-group-sm" role="group">
										<a class="btn btn-outline-info btn-sm" href=""><i class="fas fa-eye"></i> </a>
										{% if element.creator == user %}
										<a class="btn btn-outline-info btn-sm" href=""><i class="fas fa-pencil-alt"></i> </a>
										<a class="btn btn-outline-info btn-sm" href="#"><i class="fas fa-trash-alt"></i> </a>
										{% endif %}
									</div>
								</td>
							  </tr>
						  {% endfor %}
					   </tbody>
					</table>
				</div><!-- table-responsive - END -->
			</div> <!-- card-body - END -->
		</div> <!-- card - END -->
	</div><!-- col - END -->
</div><!-- row mt-3 - END -->
{% endif %}
<!-- Attendances table END-->

student/templates/student/student_details/student_details_guardian.html
<!-- /StudX_dir/StudX/student/templates/student/student_details/student_details_guardian.html -->

{% load i18n %}


{% for r in relationship %}
	<ul class="list-group mb-3" style="max-width:400px;">
		<li class="list-group-item d-flex justify-content-between">
			<div>
				<i class="fa fa-align-justify"></i> {{ r.parent.fname }} {{ r.parent.lname }} 
			</div>
			<div id="parent-legal-status">
				<span class="badge badge-success">{{r.get_relation_display}}</span>
				{% if r.is_InCharge %}
					<span class="badge badge-primary">{% trans "Responsible" %}</span>
				{% endif %}
				{% if r.is_ICE %}
					<span class="badge badge-danger">{% trans "Urgency" %}</span>
				{% endif %}
			</div>
		</li>
		<li class="list-group-item d-flex justify-content-between align-items-center">
			{% trans "Address" %} <span>{{ r.parent.address }}</span>
		</li>
		{% for c in r.parent.parent_hascontact.all %}
			<li class="list-group-item d-flex justify-content-between align-items-center">
				{{ c.get_type_display }} <span>{{ c.contact }}</span>
			</li>
		{% endfor %}
	</ul>
{% endfor %}

student/templates/student/student_details/student_details_profile_card.html
{#  /StudX_dir/StudX/student/templates/student/student_details/student_details_profile_card.html #}

{% load i18n %}

 <div class="card">
	<div class="card-body">
	   {% if student_record.picture %}
	   <img class="rounded-circle mx-auto d-block" src="/student{{ student_record.picture.url }}" height="100" width="100" alt="{{ student_record.fname}} {{student_record.lname}}" />
	   {% else %}
	   <img class="rounded-circle mx-auto d-block" height="100" width="100" src="/student/images/profile/default_user.jpeg" alt="default_img"/>
	   {% endif %}
	   <h4 class="profile-username text-center">{{ student_record.fname}} {{student_record.lname}}</h4>
	   <ul class="list-group">
		  <li class="list-group-item"><b>{% trans "Matricule" %}</b><a class="float-right text-aqua">{{ student_record.matricule }}</a></li>
		  <li class="list-group-item"><b>{% trans "Classe"%}</b><a class="float-right text-aqua">{{ student_record.classe.classe_name }}</a></li>
		  <li class="list-group-item"><b>{% trans "Gender" %}</b><a class="float-right text-aqua">{{ student_record.get_gender_display }}</a></li>
		  <li class="list-group-item"><b>Age</b><a class="float-right text-aqua">{{ student_record.get_age }}</a></li>
	   </ul>
	</div>
 </div>