StudX/urls.py
from django.urls import path, include
from django.conf.urls import url
from django.shortcuts import redirect
from django.views.generic import TemplateView

import dashboard.urls, student.urls, user.urls, communication.urls, configuration.urls, schedule.urls

# Simple views for new pages
def teachers_view(request):
    from django.shortcuts import render
    return render(request, 'teachers_list.html')

def formations_view(request):
    from django.shortcuts import render
    return render(request, 'formations_list.html')

def payments_view(request):
    from django.shortcuts import render
    return render(request, 'payments_list.html')

urlpatterns = [
    url(r'^tinymce/', include('tinymce.urls')),
    path('', lambda request: redirect('dashboard:dashboard'), name='root'),
    path('schedule/', include(schedule.urls, namespace='schedule')),
    path('configuration/', include(configuration.urls, namespace='configuration')),
    path('communication/', include(communication.urls, namespace='communication')),
    path('user/', include(user.urls, namespace='user')),
    path('dashboard/', include(dashboard.urls, namespace='dashboard')),
    path('student/', include(student.urls, namespace='student')),
    # New pages
    path('teachers/', teachers_view, name='teachers'),
    path('formations/', formations_view, name='formations'),
    path('payments/', payments_view, name='payments'),
]

user/urls.py
# /StudX_dir/StudX/user/urls.py

from django.urls import path
from django.conf.urls.static import static
from django.conf.urls import url
from user.forms import CustomAuthForm
from django.contrib.auth import views as auth_views

from user import views

app_name = 'user'

urlpatterns = [
	url(r'^logout/$', views.logout_studx, name='logout'),
	path('login/', auth_views.LoginView.as_view(), name='login'),
	path('logout/', auth_views.LogoutView.as_view(), name='Logout'),
	path('list/', views.user_list, name='user_list'),
	path('new/', views.create_edit_user, name='create_user'),
	path('<int:user_id>/edit/', views.create_edit_user, name='edit_user'),
	path('<int:user_id>/delete/', views.delete_user, name='delete_user'),
]

user/models.py
# /StudX_dir/StudX/user/models.py

from django.conf import settings
from django.db import models
from django.contrib.auth.models import User, AbstractUser
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.translation import gettext as _ # for internationalization

from configuration.models import Classes, Subjects
from user.utils import ROLE_CHOICES

# Create your models here.

class User(AbstractUser):
	__tablename__ = 'User'

	role = models.PositiveSmallIntegerField(choices=ROLE_CHOICES, null=True, blank=True)
	classe_ownership = models.ManyToManyField(to='configuration.Classes', related_name='owner_classe', through='ClasseOwnership', blank=True)
	subject = models.ManyToManyField(to='configuration.Subjects', related_name='subjects_taught', blank=True)
	
	def __str__(self):
		return '{}'.format(self.username)

class ClasseOwnership(models.Model):
	__tablename__ = 'Classe Ownership'
	
	user = models.ForeignKey(to='User', on_delete=models.CASCADE, related_name='+')
	classe = models.ForeignKey(to='configuration.Classes', on_delete=models.CASCADE, related_name='+')

	def __str__(self):
		return '{} - {}'.format(self.user.username, self.classe.classe_name)

user/forms.py
# /StudX_dir/StudX/user/forms.py

from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django.forms.widgets import PasswordInput, TextInput
from user.models import User

class CustomAuthForm(AuthenticationForm):
    username = forms.CharField(widget=TextInput(attrs={'class':'validate','placeholder': 'Username'}))
    password = forms.CharField(widget=PasswordInput(attrs={'placeholder':'Password'}))
	
class CustomUserCreationForm(UserCreationForm):
	class Meta(UserCreationForm):
		model = User
		fields = ('username', 'first_name', 'last_name', 'email', 'role', 'is_active', 'groups', 'classe_ownership', 'subject')

class CustomUserChangeForm(UserChangeForm):
	class Meta(UserCreationForm):
		model = User
		fields = ('username', 'first_name', 'last_name', 'email', 'role', 'is_active', 'groups', 'classe_ownership', 'subject')
		exclude = ('password1','password2',)

user/views.py
# /StudX_dir/StudX/user/views.py

import random
import string

from django.shortcuts import render, redirect, get_object_or_404

from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout, authenticate, login


# import class from models
from user.models import User, ClasseOwnership
from configuration.models import Classes, Subjects
from django.contrib.auth.models import Group

#import class from forms
from .forms import CustomUserCreationForm, CustomUserChangeForm


def logout_studx(request):
    logout(request)
    request.session.flush()
    return redirect('user:login')

@login_required
def user_list(request):

	user_list = User.objects.all().exclude(is_superuser=True)
	
	variables = {
		'user_list': user_list,
	}
	
	template = 'user/user_list.html'

	return render(request, template, variables)
	
	
@login_required
def create_edit_user(request, user_id=None):
	
	if not request.user.has_perm('user.add_user') and request.user.has_perm('user.edit_user') : 
		return HttpResponseForbidden()

	if user_id:
		user = get_object_or_404(User, id=user_id)
	else:
		user = User()
	
	temp_password = ''.join([random.choice(string.ascii_letters+string.digits+'-_') for ch in range(8)])
	
	if request.method == 'POST':
		if user_id:
			form = CustomUserChangeForm(request.POST, instance=user)
		else: form = CustomUserCreationForm(request.POST, instance=user)
		if form.is_valid():
			user_instance = form.save(commit=False)
			
			if user_id:
				user_instance.password = user.password
			
			user_instance.save()
			
			# assign role to a user
			user.groups.clear()
			for role in form.cleaned_data['groups']:
				group = Group.objects.get(name=role)
				user.groups.add(group)
			
			# assign classes to a user
			user.classe_ownership.clear()
			for classe in form.cleaned_data['classe_ownership']:
				classe = Classes.objects.get(classe_name=classe)
				ClasseOwnership.objects.create(user=user, classe=classe)
				
			# assign subjects to a user
			user.subject.clear()
			print(form.cleaned_data.get('subject'))
			for subject in form.cleaned_data['subject']:
				# subject = Subjects.objects.get(name=subject)
				user.subject.add(subject) 

			return redirect('user:user_list')
		else : 
			print("CustomUserCreationForm is invalid")
			print("errors: ", form.errors)
	else: form = CustomUserCreationForm(instance=user)
	
	variables = {
		'form': form,
		'user': user,
		'temp_password': temp_password,
	}
	
	template = 'user/user_form.html'

	return render(request, template, variables)
	
@login_required
def delete_user(request, user_id):
	if user_id:
		if request.user.has_perm('user.delete_user'):
			user = get_object_or_404(User, pk=user_id)
			user.delete()
			return redirect('user:user_list')
		else: return HttpResponseForbidden()
	else: return Http404()

user/templates/user/register.html
{% extends "base.html" %}
{% block main %}
<h1>Register for StudX</h1>
<form method="post"> 
	{{ form.as_p }} {% csrf_token %}
	<button type="submit" class="btn btn-primary">
		Register
	</button>
</form>
{% endblock %}

user/templates/user/user_delete_modal.html
{# /StudX_dir/StudX/user/templates/user/user_delete_modal.html #}

{% load i18n %}

<!-- User Delete Modal -->
<div class="modal" id="UserDeleteModal">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-body">{% trans "Are you sure ?" %}</div>
			<div class="modal-footer">
				<form action="" method='POST'>
				{% csrf_token %}
					<button type="button" class="btn btn-danger" data-dismiss="modal">{% trans "Cancel" %}</button>
					<a class="btn btn-secondary" href="{% url 'user:delete_user' user.id %}">{% trans "Confirm" %}</a>
				</form>
			</div>
		</div>
	</div>
</div> <!-- User Delete Modal - END -->

user/templates/user/user_form.html
{# /StudX_dir/StudX/user/templates/user/user_form.html #}

{% extends 'dashboard_base.html' %}
{% load static i18n widget_tweaks %}

{% block content %}

<div class="container"> 
	<div class="card w-75 mb-2"> 
		<div class="card-header">
			{% if user.id %}{% trans 'Edit user details' %}{% else %}{% trans 'Create new user' %}{% endif %}
		</div>
		<div class="card-body"> 
			<form method="post">
			{% csrf_token %}
				{{ form.non_field_errors }}
			{% for hidden_field in form.hidden_fields %}
				{{ hidden_field.errors }}
				{{ hidden_field }}
			{% endfor %}
				
				<div class="form-group row">
					<label for="{{ form.is_active.id_for_label }}" class="col-sm-2 col-form-label">{% trans 'Status' %}</label>
					<div class="col-sm-10">
					
						<label class="switch ">
							{%  render_field form.is_active class="success" %}
						  <span class="slider round"></span>
						</label>
						
					</div>
				</div>
				<div class="form-group row">
					<label for="{{ form.groups.id_for_label }}" class="col-sm-2 col-form-label">{% trans 'Role' %}</label>
					<div class="col-sm-10">
					{%  render_field form.groups|attr:"multiple" class="selectpicker"  data-max-options="1" %}
					</div>
				</div>
				<div class="form-group row">
					<label for="{{ form.username.id_for_label }}" class="col-sm-2 col-form-label">{% trans 'Username' %}</label>
					<div class="col-sm-10">
					{%  render_field form.username class="form-control" %}
					</div>
				</div>
				<div class="form-group row">
					<label for="{{ form.first_name.id_for_label }}" class="col-sm-2 col-form-label">{% trans 'First name' %}</label>
					<div class="col-sm-10">
					{%  render_field form.first_name class="form-control" %}
					</div>
				</div>
				<div class="form-group row">
					<label for="{{ form.last_name.id_for_label }}" class="col-sm-2 col-form-label">{% trans 'Last name' %}</label>
					<div class="col-sm-10">
					{%  render_field form.last_name class="form-control" %}
					</div>
				</div>
				<div class="form-group row">
					<label for="{{ form.email.id_for_label }}" class="col-sm-2 col-form-label">{% trans 'Email address' %}</label>
					<div class="col-sm-10">
					{%  render_field form.email class="form-control" type="email" %}
					</div>
				</div>
				{% if not user.id %}
				<div class="form-group row">
					<label for="{{ form.password1.id_for_label }}" class="col-sm-2 col-form-label">{% trans 'Password' %}</label>
					<div class="col-sm-10">
						{%  render_field form.password1 class="form-control" type="password" %}
						<small id="{{ form.password1.id_for_label }}" class="form-text text-muted">
							{% trans "suggestion: " %}{{ temp_password }}
						</small>
					</div>
					
				</div>
				<div class="form-group row">
					<label for="{{ form.password2.id_for_label }}" class="col-sm-2 col-form-label">{% trans 'Password confirmation' %}</label>
					<div class="col-sm-10">
					{%  render_field form.password2 class="form-control" type="password" %}
					</div>
				</div>
				{% endif %}
				<div class="form-group row">
					<label for="{{ form.classe_ownership.id_for_label }}" class="col-sm-2 col-form-label">{% trans 'Classes' %}</label>
					<div class="col-sm-10">
					{%  render_field form.classe_ownership|attr:"multiple" class="selectpicker"  data-max-options="" %}
					</div>
				</div>
				<div class="form-group row">
					<label for="{{ form.subject.id_for_label }}" class="col-sm-2 col-form-label">{% trans 'Subjects' %}</label>
					<div class="col-sm-10">
					{%  render_field form.subject|attr:"multiple" class="selectpicker"  data-max-options="" %}
					</div>
				</div>


				<div class="row mt-3">
					<div class="col">
						<button type="submit" class="btn btn-primary">Submit</button>
						<a class="btn btn-secondary" href="{% url 'user:user_list' %}" role="button">{% trans 'Cancel' %}</a>
					</div>
				</div>
			
			</form>
		</div>
	</div>
</div>

{% endblock %}

user/templates/user/user_item_list.html
{# /StudX_dir/StudX/user/templates/user/user_item_list.html #}

{% load i18n %}

<tr>	
	<td>
		{% if user.is_active %}
			<span class="badge badge-pill badge-success">{% trans "Active" %}</span>
		{% else %}
			<span class="badge badge-pill badge-danger">{% trans "Inactive" %}</span>
		{% endif %}
	</td>
	<td>{{ user.username }}</td>
	<td>{{ user.first_name }}</td>
	<td>{{ user.last_name }}</td>
	<td>{% for group in user.groups.all %}{{ group }}{% endfor %}</td>
	<td>
		{% if user.classe_ownership.all %}
			{% for classe in user.classe_ownership.all %}
				<span class="badge badge-info">{{ classe}}</span>
			{% endfor %}
		{% else %} -
		{% endif %}
	</td>
	<td>{{ user.email }}</td>
	<td class="actions align-middle">
		<div class="btn-group btn-group-sm" role="group">
		{% if perms.user.change_user %}
			<a class="btn btn-outline-info btn-sm" href="{% url 'user:edit_user' user.id %}"><i class="fas fa-pencil-alt"></i></a>
		{% endif %}
		{% if perms.user.delete_user %}
			<a class="btn btn-outline-info btn-sm" data-toggle="modal" data-target="#UserDeleteModal" href="#"><i class="fas fa-trash-alt"></i></a>
		{% endif %}
		</div>
		{% include 'user/user_delete_modal.html' %}
	</td>
</tr>

user/templates/user/user_list.html
{# /StudX_dir/StudX/user/templates/user/user_list.html #}

{% extends 'dashboard_base.html' %}
{% load static i18n %}

{% block title %}User{% endblock %}

{% block content %}

<div class="card">  
{% include 'user/user_list_filter.html' %} 	
	<div class="card-body"> 
	{% if user_list %}
		<table class="table table-responsive-sm table-hover table-outline" id="UserdataTable" cellspacing="0">
			<thead>
				<tr>
					<th>{% trans "Status" %}</th>
					<th>{% trans "Username" %}</th>
					<th>{% trans "Firstname" %}</th>
					<th>{% trans "Lastname" %}</th>
					<th>{% trans "Role(s)" %}</th>
					<th>{% trans "Classe(s)" %}</th>
					<th>{% trans "Email" %}</th>
					<th class="nosort">Action</th>
				</tr>
			</thead>
			<tbody>
			{% for user in user_list %}
				{% include 'user/user_item_list.html' %}
			{% endfor %}
			</tbody>
				<tr></tr>
			<tfoot></tfoot>
		</table>
		
	{% else %}
		{% trans "No result" %}
	{% endif %}
	</div>
</div>

{% endblock %}

{% block extra_js %}
	<script src="{% static 'js/datatables/datatables.js' %}"></script>
{% endblock extra_js %}

user/templates/user/user_list_filter.html
{# /StudX_dir/StudX/user/templates/user/user_list_filter.html #}

{% load i18n %}

<nav class="navbar navbar-light bg-light justify-content-between">
	<div class="btn-group" role="group" aria-label="First group">
		<button type="button" class="btn btn-sm btn-outline-secondary" disabled>Total: {{ user_list|length }}</button>
	</div>

	<div class="btn-group float-right" role="group">
	{% if perms.user.add_user %}
		<a class="btn btn-secondary btn-sm" href="{% url 'user:create_user' %}"><i class="fa fa-plus" aria-hidden="true"></i></a>
	{% endif %}
		<a class="btn btn-sm btn-secondary" href="#"><i class="fas fa-flag"></i></a>
	</div>

</nav>